version: '2'

services:

  db-server:
    build: ./db-server
    image: ht/mysql
    container_name: htdb
    networks:
     - net
    ports:
     - "3306:3306" # "host:container"
    volumes:
    # DDL init scripts (.sh, .sql, .sql.gz) to create users,
    # db's, etc., goes in /docker-entrypoint-initdb.d and are
    # automatically read and executed in alphabetical order
    # when a container is started for the first time.
    - ./db-server/initdb:/docker-entrypoint-initdb.d
    - ./db-server/private:/opt/mysql/private

  app-server:
    build: ./app-server
    image: ht/tomcat
    container_name: htapp
    depends_on:
     - db-server
    networks:
     - net
#    expose:
#     - "8009"
    ports:
     - "8080:8080" # "host:container"
    volumes:
     - ./app-server/private:/opt/tomcat/conf/private
     #- ./app-server/shared/lib:/opt/tomcat/shared/lib
     - ./app-server/wars:/usr/share/wars

  web-server:
    build: ./web-server
    image: ht/apache
    container_name: htweb
#    hostname: localhost.byu.edu
    depends_on:
     - app-server
    networks:
     - net
#    expose:
#     - "80"
#     - "443"
    ports:
     - "80:80" # "host:container"
     - "443:443"
     #- "8009:8009" # Tomcat Java
     #- "8005:8005" # Tomcat shutdown
    volumes:
     - ./web-server/certs:/usr/local/apache2/conf/certs
     #- ./web-server/public-html:/usr/local/apache2/htdocs

networks:
  net:
